version: '3'
services:
  usocial-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    container_name: usocial-back
  usocial-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "81:80"
    container_name: usocial-front